spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crud-produto-pedido-itens
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      default_schema: public

    show-sql: true

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG

  server:
    error:
      include-stacktrace: never
    port: 8080

  config:
    import: optional:file:.env[.*]

  flyway:
    enabled: true
    locations: classpath:db/migration
